name: Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  static-tests:
    name: Static Tests (Metadata & Templates)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run static tests (metadata)
        run: pytest tests/test_skill_metadata.py tests/test_manifest_consistency.py -v

      - name: Run template tests
        run: pytest tests/test_template_assets.py -v

  unit-tests:
    name: Unit Tests (Python)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: pytest tests/unit/ -v --tb=short

      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-results
          path: pytest-results/

  e2e-smoke-tests:
    name: E2E Smoke Tests (Main Branch Only)
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run E2E smoke tests
        run: |
          # Run smoke tests only (quick validation)
          pytest tests/e2e/ -v -m "not expensive" --tb=short || echo "E2E tests skipped (requires Claude CLI setup)"
        continue-on-error: true
